### ISSUE TITLE
Plugin Draggable: Dragging an element downwards inserts it in wrong order

### ISSUE THREAD

**Issue by dsheyp** [phphe/he-tree-vue#50] opened 2021-04-12 08:20 UTC
Hi

I'm using v2.0.8 with the plugins Fold, Check, Draggable as in your [Demo](https://he-tree-vue.phphe.com/)

When an elment is dragged downwards after dropping it will be inserted at index `(placeholderIndex - 1)` instead of `(placeholderIndex)`. Dragging an element upwards works as expected.

Any ideas what's going wrong here?

Thanks
dsheyp

**Comment by phphe** [comment] 2021-04-12 09:59
after drop, node will be inserted to targetPath. targetPath is same with placeholder path.

**Comment by dsheyp** [comment] 2021-04-12 11:37
hi

many thanks for your response. please see screencast video for details 

https://drive.google.com/file/d/1n1j63kIzEO4imCpWOhZNmPQUv2AlyevH/view?usp=sharing

**Comment by phphe** [comment] 2021-04-12 12:09
Hello

Can you create a reproduce in codesandbox.io, because it works well in our demo.

**Comment by dsheyp** [comment] 2021-04-12 14:46
Hi many thanks for your answer

Tree.vue was slightly modified due to incompatibilities with jsx

Please see https://codesandbox.io/s/laughing-cerf-buenv for more details

Thank you
dsheyp

**Comment by phphe** [comment] 2021-04-12 15:41
Thank you for report. It is a bug since 2.0.8. You can install previous version 2.0.7. I am fixing it.

**Comment by phphe** [comment] 2021-04-12 16:19
fixed in 2.0.9

**Closed as completed** 2021-04-12 16:18 UTC
