### ISSUE TITLE
Using he-tree-vue with nuxt throws an error on draggable on refresh

### ISSUE THREAD

**Issue by websiddu** [phphe/he-tree-vue#7] opened 2020-03-21 01:58 UTC
First off thanks a lot for great work. 

I'm using he-tree-vue in my nuxt project, this works perfectly when the server just started. But once the page is refreshed it shows the following error when dragging. 

![image](https://user-images.githubusercontent.com/968912/77217091-ccd3bf80-6adc-11ea-8be9-d1b48defb06a.png)

**Comment by phphe** [comment] 2020-03-21 03:06
Does the page be refreshed by hot reload? I created a nuxt project with he-tree-vue 1.1.2, it works well with hot reload. Could you create a reproduce or show your code?

**Comment by websiddu** [comment] 2020-03-21 03:37
It renders very well no problems with that. 

For the first time when I drag an element it works fine. 
If I reload the page, by hitting the refresh button and then try again it will throw that error above. 

I think it got to do with the way the code is setting the id's so in nuxt `this._uid` are generated twice server side and the client side. But the code stores the server generated Vue Instances, but when all the scripts are loaded the `data-tree-id` are updated on the client side making  startTree not findable as we lost the ids. 

Personal opinion: 
Using _uid is not recommended, it causes a ton of problems in the future. 
Also finding the Vue instance by data attribute seems flakey. 
May be consider using `this.$el` or `this` to find the Vue element or have a global window object?

**Comment by phphe** [comment] 2020-03-21 03:40
I got that, let me check.

**Comment by phphe** [comment] 2020-03-21 04:37
fixed in 1.1.4 the issue is nuxt does not update template with latest id. So I reassign treeId after mounted.

**Closed as completed** 2020-04-09 13:52 UTC
