### ISSUE TITLE
Using getNodeParentByPath for a dragged node

### ISSUE THREAD

**Issue by rubinovk** [phphe/he-tree-vue#20] opened 2020-06-10 13:38 UTC
Hi, 

I am working with a Draggable plugin. 
How can I access the parent of the dragged node?
I see `getNodeParentByPath` method, but how do I call it?

```
<template>
  <Tree
    :value="categoryTreeData"
    draggable
    droppable @drop="handleTreeChange"
  >
    <span slot-scope="{node, index, path, tree}">
      <template v-if="!node.isDragPlaceHolder">
        <span
          v-if="node.children && node.children.length"
          @click="slot.store.toggleOpen(node)"
        >
          <v-icon v-if="node.open" small class="mr-1">mdi-minus-box-outline</v-icon>
          <v-icon v-if="!node.open" small class="mr-1">mdi-plus-box-outline</v-icon>
        </span>
        <span :class="{ 'draggable-node--drop-disabled': node.droppable === false }">{{ node.text }}</span>
      </template>
    </span>
  </Tree>
</template>
<script>
import { Tree,  Draggable } from "he-tree-vue"
import 'he-tree-vue/dist/he-tree-vue.css'
import sortBy from 'lodash/sortBy'

export default {
  name: 'CategoryTreeSort',
  components: {Tree: Tree.mixPlugins([Draggable])},
  methods: {
    async handleTreeChange (store) {
       const {dragNode} = store
       // how to get the parent of dragNode?
    }
....
```

Thank you

**Comment by phphe** [comment] 2020-06-10 13:57
If dragNode not be dropped, its path is store.startPath, else store.targetPath.
```js
getNodeParentByPath(store.startPath)
getNodeParentByPath(store.targetPath)
```
But in current version `1.*.*`, in drop event, the dragNode is not be dropped. It will be fixed in next version `2.*.*`. So if you want get parent node after dropped:
```html
<Tree ref="tree" @change="handleTreeChange">
```
```js
handleTreeChange () {
    const store = this.$refs.tree.treesStore.store
    const {dragNode} = store
    // get the parent of dragNode
    getNodeParentByPath(store.startPath)
    getNodeParentByPath(store.targetPath)
}
```

**Comment by phphe** [comment] 2020-06-12 09:39
Now v2 pulished. You can use
```js
getNodeParentByPath(store.startPath)
getNodeParentByPath(store.targetPath)
```

**Closed as completed** 2020-06-13 14:01 UTC

**Comment by rubinovk** [comment] 2020-06-13 14:30
Thanks! I will use it now

**Comment by bajki** [comment] 2020-07-08 08:06
I get this error 

[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'store' of undefined"

**Comment by phphe** [comment] 2020-07-08 08:41
@bajki  could you show more?

**Comment by bajki** [comment] 2020-07-08 08:45
https://codesandbox.io/s/quirky-diffie-ssrrm

Could you update this to show us how it works?

Because i need parent_id to update sql

**Comment by phphe** [comment] 2020-07-08 09:01
@bajki `treesStore`, not `treeStore`

**Comment by AlexKonovalik** [comment] 2023-01-12 14:25
Hi! 
The `getNodeParentByPath` method returns an incorrect node
It returns the next one after the correct node if I move from top to bottom

**Comment by phphe** [comment] 2023-01-12 14:50
try both 
```
getNodeParentByPath(store.startPath)
getNodeParentByPath(store.targetPath)
```
If dragNode not be dropped, its path is store.startPath, else store.targetPath.

**Comment by AlexKonovalik** [comment] 2023-01-12 15:15
I've tried both variants But the path on drop is incorrect because I move the node from top to bottom
For example, I move the node with startPath [0, 7]
On drop it has targetPath [0, 8, 0], but it should be [0, 7, 0] because I moved one node from top

**Comment by phphe** [comment] 2023-01-13 17:21
@AlexKonovalik Could you create a reproduce on codepen or other sites?

**Comment by AlexKonovalik** [comment] 2023-01-13 19:18
@phphe Shure!
There is a link
https://codesandbox.io/s/pensive-wilbur-rbwr5f?file=/src/App.vue

IMHO, the problem is not even in `getNodeParentByPath` method, but in the `targetPath`

**STR:**
1. Move` node 1-7` to `node 1-8` (before `node 1-8-1`)
2. Check console logs

**Actual result:** 
1. `targetPath` is [0, 7, 0]
2. Parent node is 1-9

**Expected result:** 
1. `targetPath` should be [0, 6, 0]
2.  Parent node should be 1-8

**Comment by phphe** [comment] 2023-01-14 13:56
@AlexKonovalik use he-tree-vue@3.1.0

**Comment by AlexKonovalik** [comment] 2023-01-16 08:33
@phphe Thanks! It works correctly in this version
